# Generated by Django 3.2.7 on 2021-10-08 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='main/default.jpg', null=True, upload_to='profile_pics/')),
                ('phone', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('st', 'Student'), ('t', 'Teacher')], default='st', max_length=3)),
                ('enrolled', models.ManyToManyField(blank=True, related_name='users', to='courses.Course')),
                ('finished', models.ManyToManyField(blank=True, related_name='users_finished', to='courses.Course')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
    ]
