# Generated by Django 3.2.7 on 2021-11-11 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_approved'),
        ('ecommerce', '0003_auto_20211105_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='withdrawn_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='referring_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='courses.course'),
        ),
    ]
