# Generated by Django 3.2.7 on 2021-10-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, default='main/default.jpg', null=True, upload_to='testimonials/'),
        ),
    ]
