# Generated by Django 3.2.7 on 2021-10-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('courses', '0005_mcq_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='completed',
            field=models.ManyToManyField(blank=True, related_name='completed_mcqs', to='users.Profile'),
        ),
    ]
