# Generated by Django 3.2.7 on 2021-10-13 10:34

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('courses', '0006_alter_mcq_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcq',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='mcqtranslation',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='mcqtranslation',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='mcqtranslation',
            name='option3',
        ),
        migrations.AddField(
            model_name='mcq',
            name='serial_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='McqOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.ManyToManyField(blank=True, related_name='completed_mcqs', to='users.Profile')),
                ('mcq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='courses.mcq')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='McqOptionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=300)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='courses.mcqoption')),
            ],
            options={
                'verbose_name': 'mcq option Translation',
                'db_table': 'courses_mcqoption_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
