# Generated by Django 3.2.7 on 2021-10-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('courses', '0008_auto_20211013_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcq',
            name='completed',
        ),
        migrations.AddField(
            model_name='mcqoption',
            name='completed',
            field=models.ManyToManyField(blank=True, related_name='completed_mcqs', to='users.Profile'),
        ),
    ]
