# Generated by Django 3.2.7 on 2021-10-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('courses', '0009_auto_20211013_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcqoption',
            name='completed',
        ),
        migrations.AddField(
            model_name='mcq',
            name='completed',
            field=models.ManyToManyField(blank=True, related_name='completed_mcqs', to='users.Profile'),
        ),
    ]
