# Generated by Django 3.2.7 on 2021-10-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20211013_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='main/')),
            ],
        ),
    ]
